### ISSUE TITLE
MCTS: IllegalArgumentException on simulation

### ISSUE THREAD

**Issue by LeftistTachyon** [LeftistTachyon/GameAI#3]
`Exception in thread "main" java.lang.IllegalArgumentException: bound must be positive`  
`at java.util.Random.nextInt(Random.java:388)`  
`at common.TreeNode.simulate(TreeNode.java:148)`  
`at common.TreeNode.selectAction(TreeNode.java:77)`  
`at common.GameAIMain.main(GameAIMain.java:21)`

**Comment by LeftistTachyon** [comment]
Resolved
