### ISSUE TITLE
MCTS Test: IndexOutOfBoundsException during simulation

### ISSUE THREAD

**Issue by LeftistTachyon** [LeftistTachyon/GameAI#4]
`Exception in thread "main" java.lang.IndexOutOfBoundsException: 7 over 1`  
`at common.Board.movePiece(Board.java:336)`  
`at common.GameAIMain.main(GameAIMain.java:27)`

**Comment by LeftistTachyon** [comment]
Forgot a `cb.recalculateMoves();`
