### ISSUE TITLE
MCTS: does not work in positions other than the starting pos

### ISSUE THREAD

**Issue by LeftistTachyon** [LeftistTachyon/GameAI#5]
IllegalArgumentExceptions, NullPointerExceptions galore!

**Comment by LeftistTachyon** [comment]
Exception in thread "main" java.lang.IndexOutOfBoundsException: 1 over 1
	at common.Board.movePiece(Board.java:336)
	at common.TreeNode.expand(TreeNode.java:108)
	at common.TreeNode.selectAction(TreeNode.java:83)
	at common.GameAIMain.main(GameAIMain.java:20)
Java Result: 1

**Comment by LeftistTachyon** [comment]
Fixed
