### ISSUE TITLE
ChessAI: can't keep track of King

### ISSUE THREAD

**Issue by LeftistTachyon** [LeftistTachyon/GameAI#9]
Exception in thread "main" java.lang.ClassCastException: chess.Knight cannot be cast to chess.King
	at chess.ChessBoard.pieceFromTo(ChessBoard.java:108)
	at common.Board.movePiece(Board.java:303)
	at common.Board.movePiece(Board.java:286)
	at common.Board.movePiece(Board.java:367)
	at common.TreeNode.simulate(TreeNode.java:168)
	at common.TreeNode.selectAction(TreeNode.java:90)
	at common.GameAIMain.main(GameAIMain.java:20)

**Comment by LeftistTachyon** [comment]
This happens when you eat the king. I think this is a problem with king moves after check
